### ISSUE TITLE
Problema con las lecturas matutinas

### ISSUE THREAD

**Issue by nepito** [IslasGECI/islasgeci.github.io#48]
En la entrada [Qué hacer cuando me quedo sin trabajo](https://islasgeci.github.io/2018/09/26/que_hacer_cuando_estoy_desocupado) hacemos referencia a la entrada [Lecturas matutinas](https://islasgeci.github.io/2018/09/03/lecturas_matutinas), pero el [link](https://islasgeci.github.io/2018/09/26/lecturas_matutinas.md) es el incorrecto, está roto. 
- [ ] Por favor actualiza la liga

**Comment by evaristor** [comment]
Gracias @nepito. [Aquí](https://github.com/IslasGECI/islasgeci.github.io/pull/50) lo resolví. Por favor le podrías echar un :eyes:?

**Comment by evaristor** [comment]
Resuelto en #50
